url: http://deviparikh.com
title: Devi Parikh
author:
  name: Devi Parikh
  email: deviparikh.dp@gmail.com
description: AI Researcher, Generative Artist.
# permalink: /posts/:title/
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
ga_id: UA-119138789-1
